- _config.yml
- _includes/head.html
- _layouts/page.html
- chapter01/_posts/20-01-07-test.md
- chapter01/_posts/21-01-07-optimization_problems.md
- chapter01/_posts/21-01-28-brief_history_of_convex_optimization.md
- chapter01/_posts/21-01-28-convex_optimization_problem.md
- chapter01/_posts/21-01-28-goals_and_topics.md
- Activate markdown
- Fix page template to show contents on each chapter pages
> Activate markdown and Fix page template to show contents

- contribution/_posts/21-02-03-conventions.md
Image 삽입 Convention에 대한 내용을 추가했습니다.
> docs: Add image convention

- contribution/_posts/21-02-03-conventions.md
- Update posting conventions
- Add Latex Convention
- Add "order" and "owner" as new required header field
> Update Convention: update Header field convention and add latex convention

- CODEOWNERS
- Create `CODEOWNERS` (Related Issue: #22 )
- [GitHub Docs](<https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners#codeowners-syntax>)
- [GitHub Blog](<https://github.blog/2017-07-06-introducing-code-owners/>)
```
* @enfow
chapter01/ @enfow
chapter02/ @RRoundTable
chapter03/ @LEEMINJOO
chapter04/ @YoungJaeChoung
chapter05/ @hunhoon21
chapter06/ @enfow
chapter07/ @enfow
chapter08/ @enfow
chapter09/ @enfow
chapter10/ @RRoundTable
chapter11/ @RRoundTable
chapter12/ @RRoundTable
chapter13/ @RRoundTable
chapter14/ @LEEMINJOO
chapter15/ @LEEMINJOO
chapter16/ @LEEMINJOO
chapter17/ @LEEMINJOO
chapter18/ @hunhoon21
chapter19/ @hunhoon21
chapter20/ @hunhoon21
chapter21/ @hunhoon21
chapter22/ @YoungJaeChoung
chapter23/ @YoungJaeChoung
chapter24/ …
```
> Initialize CODEOWNERS system

- .github/workflows/closed_issue.yml
- _layouts/post.html
- src/change_issue_title.py
- src/requirements.txt
#39 PR을 새로운 branch로 작업했습니다. 
변경사항과 내용은 동일합니다.
> Add comments using utterance

- chapter18/_posts/20-01-08-test.md
- chapter18/_posts/21-03-23-18_00_Quasi_Newton_methods.md
- chapter18/_posts/21-03-23-18_01_Secant_Equation_and_Curvature_Condition.md
- chapter18/_posts/21-03-23-18_02_Symmetric_Rank_One_Update_(SR1).md
- chapter18/_posts/21-03-23-18_03_Davidon_Fletcher_Powell_(DFP)_Update.md
- chapter18/_posts/21-03-23-18_04_Broyden_Fletcher_Goldfarb_Shanno_(BFGS)_update.md
- chapter18/_posts/21-03-23-18_05_The_Broyden_Class.md
- chapter18/_posts/21-03-23-18_06_Superlinear_convergence.md
- chapter18/_posts/21-03-23-18_07_Limited_Memory_BFGS_(LBFGS).md
Migrate all chapter18 postings
> Chapter 18 Quasi Newton methods Migration

- chapter19/_posts/20-01-08-test.md
- chapter19/_posts/21-03-24-19_00_Proximal_Newton_Method.md
- chapter19/_posts/21-03-24-19_01_00_Proximal_Newton_method.md
- chapter19/_posts/21-03-24-19_01_01_Reminder:_proximal_gradient_descent.md
- chapter19/_posts/21-03-24-19_01_02_Proximal_Newton_method.md
- chapter19/_posts/21-03-24-19_01_03_Scaled_proximal_map.md
- chapter19/_posts/21-03-24-19_02_Backtracking_line_search.md
- chapter19/_posts/21-03-24-19_03_When_would_we_use_proximal_Newton?.md
- chapter19/_posts/21-03-24-19_04_Convergence_analysis.md
- chapter19/_posts/21-03-24-19_05_Notable_examples.md
- chapter19/_posts/21-03-24-19_06_Proximal_quasi_Newton_methods.md
- chapter19/_posts/21-03-24-19_07_Projected_Newton_method.md
Migrate all chapter19 postings
> Chapter19 Proximal Netwon Method Migration

- chapter20/_posts/20-01-08-test.md
- chapter20/_posts/21-03-27-20_00_Dual_Methos.md
- chapter20/_posts/21-03-27-20_01_00_Dual_(sub)gradient_methods.md
- chapter20/_posts/21-03-27-20_01_01_Convergence_Analysis.md
- chapter20/_posts/21-03-27-20_02_00_Dual_Decomposition.md
- chapter20/_posts/21-03-27-20_02_01_Dual_Decomposition_with_Equality_Constraint.md
- chapter20/_posts/21-03-27-20_02_02_Dual_Decomposition_with_Inequality_Constraint.md
- chapter20/_posts/21-03-27-20_03_Augmented_Lagrangians.md
- chapter20/_posts/21-03-27-20_04_00_A_peak_at_ADMM.md
- chapter20/_posts/21-03-27-20_04_01_ADMM.md
- chapter20/_posts/21-03-27-20_04_02_Converegence_Guarantee.md
- chapter20/_posts/21-03-27-20_04_03_ADMM_in_Scaled_Form.md
- chapter20/_posts/21-03-27-20_04_04_Example:_Alternating_Projection.md
- chapter20/_posts/21-03-27-20_05_References.md
Migrate all chapter 20 postings
> chapter20 dual methods migration 

- chapter23/_posts/20-01-08-test.md
- chapter23/_posts/21-03-28-23_01_Coordinate_descent.md
- chapter23/_posts/21-03-28-23_02_Example_linear_regression.md
- chapter23/_posts/21-03-28-23_03_Example_lasso_regression.md
- chapter23/_posts/21-03-28-23_04_Example_pathwise_coordinate.md
- chapter23/_posts/21-03-28-23_Coordinate_Descent.md
> Chapter23 - Migration

- chapter24/_posts/20-01-08-test.md
- chapter24/_posts/21-03-28-24_01_Definition.md
- chapter24/_posts/21-03-28-24_02_Example_of_integer_programs.md
- chapter24/_posts/21-03-28-24_03_Solving_integer_programs.md
- chapter24/_posts/21-03-28-24_04_Relaxations.md
- chapter24/_posts/21-03-28-24_05_Branch_and_bound_algorithm.md
- chapter24/_posts/21-03-28-24_Mixed_integer_programming.md
> Chapter 24 - migration

- chapter25/_posts/20-01-08-test.md
- chapter25/_posts/21-03-28-25_01_01_Convexification.md
- chapter25/_posts/21-03-28-25_01_02_Cutting_plane_algorithm.md
- chapter25/_posts/21-03-28-25_01_03_Gomory_cuts.md
- chapter25/_posts/21-03-28-25_01_04_Branch_and_cut_algorithm.md
- chapter25/_posts/21-03-28-25_01_Cutting_planes.md
- chapter25/_posts/21-03-28-25_02_01_Best_subset_selection.md
- chapter25/_posts/21-03-28-25_02_02_Least_mean_squares.md
- chapter25/_posts/21-03-28-25_02_Two_extended_examples.md
- chapter25/_posts/21-03-28-25_Mixed_integer_programming.md
> Chapter 25 - migration

- chapter22/_posts/20-01-08-test.md
- chapter22/_posts/21-03-28-22_01_Last_time_ADMM.md
- chapter22/_posts/21-03-28-22_02_Conditional_gradient_method.md
- chapter22/_posts/21-03-28-22_03_Convergence_analysis.md
- chapter22/_posts/21-03-28-22_04_Properties_and_variants.md
- chapter22/_posts/21-03-28-22_Conditional_Gradient_Method.md
> Chapter 22 - migration

- _layouts/page.html
> Fix page.html to show post title

- chapter09/_posts/20-01-08-09_02_convergence_analysis.md
- chapter09/_posts/20-01-08-09_05_03_example_FISTA.md
> fix post url warning msg

- chapter24/_posts/21-03-28-24_01_Definition.md
- contribution/_posts/21-01-27-how_to_contribute.md
- contribution/_posts/21-02-03-conventions.md
> Fix typos - `ch24-01` & `how to contribute`

- chapter21/_posts/21-03-29-21_03_Example_:_Lasso_regression_and_group_lasso_Regression.md
- chapter21/_posts/21-03-29-21_04_Example_:_Sparse_subspace_estimation_and_sparse_plus_low_rank_decomposition.md
#123 
그림 외의 모든 wikidocs 하이퍼링크 제거
> Change page liks to github.io in chapter21

- chapter09/_posts/20-01-08-09_02_convergence_analysis.md
> Fix incorrect hyperlink in 09-02

- chapter04/_posts/20-02-08-04_02_Convex_solution_sets.md
Fixed latex typo in chapter04-02
> Fixed latex typo in chapter04-02

- _includes/sidebar.html
- public/js/script.js
Issue raised up by @yseongjin 
The sidebar is opened on page load.
> Open sidebar on page load

- chapter01/_posts/21-01-07-01_00_Introduction.md
- chapter01/_posts/21-01-07-01_01_optimization_problems.md
- chapter01/_posts/21-01-28-01_02_convex_optimization_problem.md
- chapter01/_posts/21-01-28-01_03_goals_and_topics.md
- chapter01/_posts/21-01-28-01_04_brief_history_of_convex_optimization.md
- chapter21/_posts/21-03-29-21_06_Faster_convergence_with_subprogram_parametrization_:_example_of_the_2d_fused_lasso_problem.md
> align chapter01 contents

- chapter03/_posts/21-02-12-03_00_Convex_functions.md
- chapter03/_posts/21-02-12-03_01_00_Basic_properties_and_examples.md
- chapter03/_posts/21-02-12-03_01_01_convex_functions_definition.md
- chapter03/_posts/21-02-12-03_01_02_examples_of_convex_function.md
- chapter03/_posts/21-02-12-03_01_03_key_properties_of_convex_functions.md
- chapter03/_posts/21-02-12-03_02_operations_that_preserve_convexity.md
- chapter03/_posts/21-02-12-03_03_the_conjugate_function.md
- chapter03/_posts/21-02-12-03_04_00_Quasiconvex_functions.md
- chapter03/_posts/21-02-12-03_04_01_quasiconvex_functions_definition_and_examples.md
- chapter03/_posts/21-02-12-03_04_02_basic_properties_of_quasiconvex_functions.md
- chapter03/_posts/21-02-12-03_04_03_differentiable_quasiconvex_functions.md
- chapter03/_posts/21-02-12-03_04_04_operations_that_preserve_quasiconvexity.md
- chapter03/_posts/21-02-12-03_05_log_concave_and_log_convex_functions.md
- chapter03/_posts/21-02-12-03_06_convexity_with_respect_to_generalized_inequalities.md
> Align chapter03 contents

- chapter04/_posts/20-02-08-04_00_Convex_optimization_basics.md
- chapter04/_posts/20-02-08-04_01_Basic_terminology.md
- chapter04/_posts/20-02-08-04_02_Convex_solution_sets.md
- chapter04/_posts/20-02-08-04_03_First_order_optimality_condition.md
- chapter04/_posts/20-02-08-04_04_Partial_optimization.md
- chapter04/_posts/20-02-08-04_05_Transformations_and_change_of_variables.md
- chapter04/_posts/20-02-08-04_06_Eliminating_equality_constraints.md
- chapter04/_posts/20-02-08-04_07_Slack_variables.md
- chapter04/_posts/20-02-08-04_08_Relaxation.md
##Done
align chapter04 contents
#106
> Align chapter04 contents

- contribution/_posts/21-01-27-initial_settings.md
1. Initial Setting에 저장소의 Issue 기능 안내 추가
2. `docker-compose up`은 레포 위 임의의 위치에서 실행 가능
> Add more guidance and fix wrong direction

- contents/chapter10/_posts/21-03-22-10_03_Max_flow_and_min_cut.md
> Align math formula in 10-03

- _includes/head.html
> Add horizontal scrollbar for math formula

- contents/chapter02/_posts/21-02-08-02_01_01_Line_line segment_ray.md
- contents/chapter02/_posts/21-02-08-02_01_03_Convex-set.md
- contents/chapter02/_posts/21-02-08-02_01_04_Convex_cone.md
- contents/chapter02/_posts/21-02-11-02_02_01_Convex_sets_examples.md
- contents/chapter02/_posts/21-02-11-02_02_02_Convex_cone_examples.md
- contents/chapter02/_posts/21-02-11-02_03_Operations_that_preserve_convexity.md
- contents/chapter02/_posts/21-02-11-02_04_Generalized_inequalities.md
- contents/chapter02/_posts/21-02-11-02_05_Separating_and_supporting_hyperplanes.md
- contents/chapter02/_posts/21-02-11-02_06_01_Dual_cones.md
- contents/chapter02/_posts/21-02-11-02_06_02_Dual_generalized_inequalities.md
#163 
- 이미지 확장자 변경 `PNG` -> `png`
이게 맞는 해법인지는 모르겠네요. 
로컬 서버에서는 이미지가 정상적으로 표시됩니다.
> [HOTFIX] Change image extensions

- contents/chapter02/_posts/21-02-11-02_02_02_Convex_cone_examples.md
- contents/chapter02/_posts/21-02-11-02_03_Operations_that_preserve_convexity.md
#164 
order가 08의 형식으로하는 경우 정수가 아닌 문자열로 인식하고 있던것 같습니다.
chapter02-02-02와 chapter02-03의 order를 수정하였습니다.
변경 전
변경 후
> fixed chapter02 post order

- contents/chapter02/_posts/21-01-08-02_01_Affine_and_Convex_Sets.md
- contents/chapter02/_posts/21-02-08-02_01_01_Line_line segment_ray.md
- contents/chapter02/_posts/21-02-08-02_01_02_Affine_set.md
- contents/chapter02/_posts/21-02-08-02_01_03_Convex-set.md
- contents/chapter02/_posts/21-02-08-02_01_04_Convex_cone.md
- contents/chapter02/_posts/21-02-11-02_02_01_Convex_sets_examples.md
- contents/chapter02/_posts/21-02-11-02_02_02_Convex_cone_examples.md
- contents/chapter02/_posts/21-02-11-02_02_Some_important_examples.md
- contents/chapter02/_posts/21-02-11-02_03_Operations_that_preserve_convexity.md
#164 
다른 chapter와 동일하게 post order를 0#에서 #형식으로 바꿨습니다.
> fixed post order convention in chapter2

- home/_posts/21-02-03-makers.md
> Remove unnecessary hyperlink in main page

- contents/chapter18/_posts/21-03-23-18_03_Davidon_Fletcher_Powell_(DFP)_Update.md
- contents/chapter18/_posts/21-03-23-18_04_Broyden_Fletcher_Goldfarb_Shanno_(BFGS)_update.md
- contents/chapter18/_posts/21-03-23-18_07_Limited_Memory_BFGS_(LBFGS).md
* align formula for 18 chapter
* 18-03
* 18-04
* 18-07
> Align formula for 18 chapter

- contents/chapter22/_posts/21-03-28-22_02_Conditional_gradient_method.md
* remove wikidocs
주석처리된 이미지로 있었네요
* remove them
> remove wikidocs

- _layouts/post.html
- home/_posts/21-06-09-view-counts.md
- public/css/lanyon.css
Add view counts on Home page and all posts.
`today's view / total view`
To-Be
1. Home page
2. Post pages
> Add view counts

- contents/chapter13/_posts/21-04-05-13_03_Dual_norms.md
- contents/chapter13/_posts/21-04-05-13_04_Conjugate_function.md
* 수식 수정 (혹시 오류가 있다면 알려주시면 감사하겠습니다 🙏)
* 번역 미비된 부분 추가
> Fix - chapter13 typo 수정

- contents/chapter06/_posts/21-03-20-06_05_stochastic_gradient_descent.md
- Fix typo on 06-05
#181  (Thanks to @sjnah)
> Fix typo on 06-05

- contents/chapter06/_posts/21-03-20-06_01_gradient_descent.md
- contents/chapter06/_posts/21-03-20-06_02_01_fixed_step_size.md
- contents/chapter06/_posts/21-03-20-06_02_02_backtracking_line_search.md
- contents/chapter06/_posts/21-03-20-06_03_02_convex_function_quardratic_upper_bound.md
- contents/chapter06/_posts/21-03-20-06_03_03_convergence analysis_for_backtracking.md
- contents/chapter06/_posts/21-03-20-06_03_04_convergence_analysis_under_strong_convexity.md
- contents/chapter06/_posts/21-03-20-06_03_05_look_at_the_conditions_and_practicalities.md
- contents/chapter06/_posts/21-03-20-06_03_06_can_we_do_better.md
- contents/chapter06/_posts/21-03-20-06_04_gradient_boosting.md
- contents/chapter06/_posts/21-03-20-06_05_stochastic_gradient_descent.md
- #177 문제의 원인이 .PNG 확장자인 것을 확인하고 .png 확장자로 변경하였습니다.
- Chapter06에 Next Post가 두개 보이던 문제를 post order를 수정하여 해결하였습니다.
> fixed image extension and post order

- contents/chapter06/_posts/21-03-20-06_01_gradient_descent.md
6장 설명 중 gardient -> gradient로 오타 수정합니다.
> Fix a misspelled term on chapter 6

- contents/chapter04/_posts/20-02-08-04_01_Basic_terminology.md
- contents/chapter06/_posts/21-03-20-06_03_02_convex_function_quardratic_upper_bound.md
- contents/chapter08/_posts/20-03-29-08_01_05_example_regularized_logistic_regression.md
- contents/chapter08/_posts/20-03-29-08_01_07_example_intersection_of_sets.md
- contents/chapter08/_posts/20-03-29-08_02_04_batch_vs_stochastic_methods.md
오타 수정 및 #185 와 같이 이미지 확장자 수정하였습니다.
> fix typo and image extension for chapter 04, 06, and 08

- contents/chapter11/_posts/21-03-24-11_04_Strong_duality.md
아래 메일 피드백 반영
```text
[cshyun102@gmail.com](mailto:cshyun102@gmail.com) 님이 전송한 피드백입니다.
----------------------------------------------------------------
책제목 : 모두를 위한 컨벡스 최적화 (Convex Optimization For All)
페이지 : 11-4 Strong duality
Example: Support Vector Machine Dual 섹션의 SVM (support vector maine) 이라고 machine에 대한 오타가 있습니다! 너무 좋은 교재를 보다가 오타가 있어서 말씀드려요!
----------------------------------------------------------------
```
> fix typo on chapter 11.4

- contents/chapter03/_posts/21-02-12-03_01_01_convex_functions_definition.md
- contents/chapter03/_posts/21-02-12-03_01_02_examples_of_convex_function.md
- contents/chapter03/_posts/21-02-12-03_01_03_key_properties_of_convex_functions.md
- contents/chapter03/_posts/21-02-12-03_02_operations_that_preserve_convexity.md
- contents/chapter03/_posts/21-02-12-03_03_the_conjugate_function.md
- contents/chapter03/_posts/21-02-12-03_04_01_quasiconvex_functions_definition_and_examples.md
- contents/chapter03/_posts/21-02-12-03_04_02_basic_properties_of_quasiconvex_functions.md
- contents/chapter03/_posts/21-02-12-03_04_03_differentiable_quasiconvex_functions.md
- contents/chapter03/_posts/21-02-12-03_04_04_operations_that_preserve_quasiconvexity.md
- contents/chapter03/_posts/21-02-12-03_05_log_concave_and_log_convex_functions.md
- contents/chapter03/_posts/21-02-12-03_06_convexity_with_respect_to_generalized_inequalities.md
- equation 오타 및 형태 수정
- 03-02: proof 삭제, 올바르지 않은 증명인 것 같습니다.
> Fix equation in chapter 3

- contents/chapter03/_posts/21-02-12-03_01_03_key_properties_of_convex_functions.md
Fixes https://github.com/convex-optimization-for-all/convex-optimization-for-all.github.io/issues/236
> change | into \mid
